#!/bin/bash

usage(){
    echo "Error: incorrect number of command line arguments." 1>&2
    echo "Usage: $0 <suite name> <program name>" 1>&2
    exit 1
}

if [ ${#} -ne 2 ]; then
    usage
fi

for suites in $(cat $1); do
    ls | grep $suites.args > /dev/null
    if [ ${?} -eq 0 ]; then
    	$2 $(cat $suites.args) > $suites.out
    else 
	$2 > $suites.out
    fi
done
